-- 1) Create series table
CREATE TABLE IF NOT EXISTS public.series (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  start_date DATE,
  end_date DATE,
  venue TEXT,
  is_active BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2) Add series_id to matches
ALTER TABLE public.matches
ADD COLUMN IF NOT EXISTS series_id BIGINT;

-- 3) Add FK constraint (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'matches_series_id_fkey'
  ) THEN
    ALTER TABLE public.matches
    ADD CONSTRAINT matches_series_id_fkey
    FOREIGN KEY (series_id)
    REFERENCES public.series(id)
    ON DELETE SET NULL;
  END IF;
END $$;

-- 4) Enable RLS
ALTER TABLE public.series ENABLE ROW LEVEL SECURITY;

-- 5) Policies (mirror existing pattern)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'series' AND policyname = 'Admin full access for series'
  ) THEN
    CREATE POLICY "Admin full access for series"
    ON public.series
    FOR ALL
    USING (public.has_role(auth.uid(), 'admin'::public.app_role))
    WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'series' AND policyname = 'Public read access for series'
  ) THEN
    CREATE POLICY "Public read access for series"
    ON public.series
    FOR SELECT
    USING (true);
  END IF;
END $$;

-- 6) updated_at trigger (reuse existing function if present)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'set_series_updated_at'
  ) THEN
    CREATE TRIGGER set_series_updated_at
    BEFORE UPDATE ON public.series
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();
  END IF;
END $$;

-- 7) Helpful index for series match lookups
CREATE INDEX IF NOT EXISTS idx_matches_series_id ON public.matches(series_id);